info:
  component: zuul server app
server:
  port: 8080
spring:
  config:
    name: zuulserver
  application:
    name: zuulserver
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
zuul:
  routes:
    greetings:
      path: /greetings/**
      service-id: GREETINGS
    helloworld:
      path: /helloworld/**
      service-id: HELLOWORLD
