info:
  component: zuul server app
server:
  port: 8080
spring:
  config:
    name: zuulserver
  application:
    name: zuulserver

zuul:
  routes:
    greetings:
      path: /greetings/**
      service-id: GREETINGS
    helloworld:
      path: /helloworld/**
      service-id: HELLOWORLD
    webdemo:
      path: /webdemo/**
      service-id: WEBDEMO

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 
