server:
  port: 9001
spring:
  application:
    name: greetings
  cloud:
    config:
      enabled: false
endpoints:
  shutdown:
    enabled: true
  restart:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/